//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/4/4 20:52:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace COM
{
    public partial class Conferences {

        public Conferences()
        {
            this.Presentations = new List<Presentation>();
            OnCreated();
        }

        public int ID { get; set; }

        public string Title { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime? EndDate { get; set; }

        public string Location { get; set; }

        public virtual IList<Presentation> Presentations { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
