//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/4/4 20:52:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace COM
{
    public partial class Presentation {

        public Presentation()
        {
            OnCreated();
        }

        public int ID { get; set; }

        public int ConferenceID { get; set; }

        public int PresenterID { get; set; }

        public string PresentationTitle { get; set; }

        public DateTime DateAndTime { get; set; }

        public virtual Conferences Conferences { get; set; }

        public virtual Presenter Presenter { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
